import {
  BadgeCheck,
  BedDouble,
  Bell,
  Brain,
  Calendar,
  CalendarCheck,
  Camera,
  ChartNoAxesColumn,
  CircleDollarSign,
  ClipboardCheck,
  Clock,
  CreditCard,
  Database,
  FileText,
  Gauge,
  Globe,
  Handshake,
  Headset,
  Languages,
  Link2,
  Lock,
  Mail,
  MapPin,
  MessageSquare,
  Phone,
  Plug,
  Receipt,
  RefreshCw,
  Search,
  Send,
  ShieldCheck,
  Sparkles,
  Star,
  TrendingUp,
  Users,
  Utensils,
  Waves,
  Zap,
} from "lucide-react";

/**
 * Names allowed in content (`icon: "..."`). Content is data, so icons are
 * referenced by string and resolved here — keeps the registry a plain module.
 */
export const ICONS = {
  agenda: Calendar,
  alerta: Bell,
  bi: ChartNoAxesColumn,
  cerebro: Brain,
  citas: CalendarCheck,
  cobro: CreditCard,
  control: ShieldCheck,
  cumplimiento: ClipboardCheck,
  datos: Database,
  dinero: CircleDollarSign,
  enlace: Link2,
  equipo: Users,
  estrella: Star,
  factura: Receipt,
  habitacion: BedDouble,
  idiomas: Languages,
  instagram: Camera,
  integracion: Plug,
  llamada: Phone,
  mensaje: MessageSquare,
  correo: Mail,
  mundo: Globe,
  recepcion: Headset,
  reloj: Clock,
  restaurante: Utensils,
  reporte: FileText,
  seguridad: Lock,
  sello: BadgeCheck,
  spa: Waves,
  subir: TrendingUp,
  tarifa: Gauge,
  trato: Handshake,
  ubicacion: MapPin,
  volver: RefreshCw,
  buscar: Search,
  enviar: Send,
  chispa: Sparkles,
  rayo: Zap,
} as const;

export type IconName = keyof typeof ICONS;

export function resolveIcon(name?: string) {
  if (!name) return Sparkles;
  return ICONS[name as IconName] ?? Sparkles;
}
