/**
 * Telling our own traffic apart from the market's (CON-294).
 *
 * WHY THIS EXISTS. On 2026-09-20, the day after the measurement spine shipped,
 * 118 of the 181 rows in `site_events` — 65% — were a single visitor id with no
 * country, generated by an agent verifying a feature against `localhost:3103`.
 * The site's `.env.local` holds the LIVE Supabase service key, so every local
 * page load wrote straight into production analytics. The «Puerta A» funnel on
 * the dashboard read "2 saw the button, 1 pressed it"; both numbers were us.
 *
 * That is the failure mode worth designing against: analytics noise does not
 * announce itself. It renders as a small, plausible number and quietly becomes
 * the baseline everything later is compared to.
 *
 * Three sources of our own traffic, and they need different answers:
 *
 *   1. **A dev server or a preview deploy** writing to the production table.
 *      Answered HERE, by host: only the real domains are measurable. This is
 *      the big one and it is decided on the SERVER, because the client of a
 *      local build is exactly the thing we do not trust.
 *   2. **Our own browsers on the live site.** Answered by an opt-out marker
 *      (`?nocount=1` once, then a cookie) — see `OPTOUT_COOKIE`.
 *   3. **Crawlers.** Already handled: `/api/track` drops bot user agents, and
 *      `middleware.ts` files them as `crawler_hit` instead.
 */

/**
 * Hosts whose traffic is real. Everything else — `localhost`, `127.0.0.1`, a
 * `*.vercel.app` preview, a LAN IP — is somebody working, not somebody buying.
 *
 * Deliberately an allowlist. A denylist of "things that look like dev" is a
 * promise to predict every future dev host, and it fails silently and in the
 * expensive direction: unknown host ⇒ counted as a customer.
 */
const MEASURABLE_HOSTS = new Set(["conagentes.com", "www.conagentes.com"]);

/** Strips the port and lowercases; `host` headers carry `:3000` locally. */
function normalizeHost(host: string | null | undefined): string {
  if (!host) return "";
  return host.trim().toLowerCase().replace(/:\d+$/, "");
}

export function isMeasurableHost(host: string | null | undefined): boolean {
  return MEASURABLE_HOSTS.has(normalizeHost(host));
}

/**
 * Set once by visiting any page with `?nocount=1`, then honoured on every
 * later visit from that browser. Read on the SERVER from the request's own
 * cookie header — the browser never gets to assert its own exclusion, because
 * a flag a client can set is a flag a client can unset by accident.
 */
export const OPTOUT_COOKIE = "cga_internal";
export const OPTOUT_PARAM = "nocount";

/** Reads our marker out of a raw `Cookie:` header. */
export function hasOptOutCookie(cookieHeader: string | null | undefined): boolean {
  if (!cookieHeader) return false;
  return cookieHeader
    .split(";")
    .some((part) => part.trim().startsWith(`${OPTOUT_COOKIE}=1`));
}

/**
 * `?nocount=1` turns it on, `?nocount=0` turns it back off.
 *
 * The off switch matters more than it looks: without it, the one browser that
 * most needs to see the site exactly as a customer does — Sebastián's — would
 * be permanently excluded from its own funnel with no way back short of
 * clearing site data.
 */
export function optOutIntent(search: string): "on" | "off" | null {
  const value = new URLSearchParams(search).get(OPTOUT_PARAM);
  if (value === null) return null;
  return value === "0" || value === "false" ? "off" : "on";
}
